# Generated by Django 4.1.3 on 2022-11-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('WORKER', 'WORKER'), ('SEEKER', 'SEEKER'), ('COMPANY', 'COMPANY')], max_length=10)),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('Company_name', models.CharField(max_length=200, verbose_name='Company name(If Company)')),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability', models.BooleanField(default=True, verbose_name='Free to work')),
                ('Charge', models.PositiveIntegerField(verbose_name='Charges')),
                ('Charge_type', models.CharField(choices=[('PER_HOUR', 'PER_HOUR'), ('PER_DAY', 'PER_DAY'), ('PER_MONTH', 'PER_MONTH'), ('PER_YEAR', 'PER_YEAR')], max_length=20, verbose_name='Charge type')),
                ('Experience', models.CharField(max_length=30, verbose_name='Experience')),
                ('Description', models.CharField(max_length=200, verbose_name='Work description')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dubai.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('user', models.ManyToManyField(to='dubai.usermodel')),
            ],
        ),
    ]
