# Generated by Django 4.1.3 on 2022-11-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0003_rename_user_locationmodel_user_id_usermodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dubai.locationmodel'),
        ),
    ]
