# Generated by Django 4.1.3 on 2022-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0005_alter_locationmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company name(If Company)'),
        ),
    ]
