# Generated by Django 4.1.3 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0006_alter_usermodel_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='Company_name',
            new_name='company_name',
        ),
    ]
