# Generated by Django 4.1.3 on 2022-11-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0009_alter_usermodel_company_name_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=200, unique=True, verbose_name='Company name(If Company)'),
        ),
    ]
