# Generated by Django 4.1.3 on 2022-11-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0010_alter_usermodel_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktype', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='workersmodel',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='workersmodel',
            name='Availability',
        ),
        migrations.RemoveField(
            model_name='workersmodel',
            name='Charge',
        ),
        migrations.RemoveField(
            model_name='workersmodel',
            name='Charge_type',
        ),
        migrations.RemoveField(
            model_name='workersmodel',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='workersmodel',
            name='Experience',
        ),
        migrations.AddField(
            model_name='workersmodel',
            name='work_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='usertype',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.CreateModel(
            name='SeekersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(default=None)),
                ('duration', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=1000)),
                ('worktype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dubai.worktypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_likes', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(default=None)),
                ('seeker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dubai.seekersmodel')),
                ('worker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dubai.workersmodel')),
            ],
        ),
        migrations.AddField(
            model_name='workersmodel',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workersmodel',
            name='charge',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='workersmodel',
            name='charge_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='workersmodel',
            name='experience',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='workersmodel',
            name='worktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dubai.worktypemodel'),
        ),
    ]
