# Generated by Django 4.1.3 on 2022-11-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0011_worktypemodel_rename_user_workersmodel_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktypemodel',
            old_name='worktype',
            new_name='name',
        ),
    ]
