# Generated by Django 4.1.3 on 2022-11-05 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0013_rename_worker_likes_connectionmodel_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 2, 24, 20, 26975), max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='connectionmodel',
            unique_together={('seeker_id', 'worker_id')},
        ),
    ]
