# Generated by Django 4.1.3 on 2022-11-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0014_usermodel_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='register_date',
            field=models.DateTimeField(default=None, max_length=100),
        ),
    ]
