# Generated by Django 4.1.3 on 2022-11-06 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0023_alter_usermodel_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 19, 49, 50, 397581, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
