"""empty message

Revision ID: 442bf009bdfa
Revises: 
Create Date: 2022-11-06 16:52:42.231948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442bf009bdfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
